### ISSUE TITLE
Flugbuch nicht mehr öffenbar

### ISSUE THREAD

**Issue by Strickandrea** [AirTome/airtome.github.io#11]
Guten Tag,
am 27.04.2023 versuchte ich mein Airtome Flugbuch zu öffnen. Dabei ist ein Fehler passiert. Seither kann ich die Datei Flugbuch.xml bzw. die ZIP Datei nicht mehr öffnen. Bekomme einen Datenfehler angezeigt. Kann diesen aber nicht finden. Mittlerweile habe ich ein neues Flugbuch angelegt, Gott sei Dank sind die Flüge auf meinem Skytrack gespeichert gewesen, was mir aber fehlt sind die Kommentare zu den einzelnen Flügen. Kann mir hier vielleicht jemand helfen. 
Es steht ja immer wenn man auf Airtome zugreift der Supporter des Tages, aber wie kann man ihn kontaktieren?
Um folgende Datei geht es mir.
[Flüge Herbst2020.fb.zip](https://github.com/AirTome/airtome.github.io/files/11415454/Fluge.Herbst2020.fb.zip)
Vielen Dank für Ihre Hilfe.
Freundliche Grüße
Andrea Stedler

**Comment by AirTome** [comment]
Hallo Andrea,
normalerweise legt AirTome ja ein Backup an. Ist das nicht vorhanden?
Das Flugbuch ist prinzipiell eine ZIP-Datei. Wenn es dir das Wert ist, dann kannst du natürlich jemand beauftragen die ZIP-Datei reparieren zu lassen.
WinZip und WinRar schaffen es out-of the-box leider nicht.
Gruß Lars

**Comment by Strickandrea** [comment]
Vielen lieben Dank für die prompte Antwort. Es ist ein Datenfehler
passiert, den wir schon mit Hilfe eines Softwareexperten versucht haben zu
beheben. Es war ein Versuch wert Euch nochmals zu fragen.
Liebe Grüße Andrea

AirTome ***@***.***> schrieb am Mo., 8. Mai 2023, 08:50:
