### ISSUE TITLE
Cannot install version R554 on macOS / Ventura 13.4 

### ISSUE THREAD

**Issue by trutmann** [AirTome/airtome.github.io#12]
Hello,

When I try to install the newest version of AirTome (R554), the following alert shows up and the installer quits.

„AirTome Installationsprogramm.app“ kann nicht geöffnet werden, da Apple darin nicht nach Schadsoftware suchen kann.
Diese Software muss aktualisiert werden. Wende dich an den Entwickler, um weitere Informationen zu erhalten.
Dieses Objekt befindet sich auf dem Image „AirTome_macos_R554.dmg“. Safari hat dieses Image heute um 11:42 geladen.

I guess the installer needs a modification for running smoothly with macOS Ventura? Or is there a workaround for this?

Cheers,
Christoph

**Comment by AirTome** [comment]
Can you please contact me by mail.

**Comment by AGeissler** [comment]
Hi AirTome, is this issue being addressed? I have the same problem, in any case. Best, Achim.

**Comment by trutmann** [comment]
> Hi AirTome, is this issue being addressed? I have the same problem, in any case. Best, Achim.

Hi, the problem was that I didn't think about the gatekeeper.
Here is a guide how you can install software (eg. AitTome) bypassing the gatekeeper:
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
