### ISSUE TITLE
Airtome R555 doesnt start from the menu entry, only from terminal window

### ISSUE THREAD

**Issue by ezfox** [AirTome/airtome.github.io#15]
After updating to R555, Airtome does not start anymore from the Linux Mint Menu.
The loading screen appears, but after it closed, the main window never appears.
When started from an open terminal window, it loads normally.
After downgrade to R554, it starts from Menu again.

**Comment by AirTome** [comment]
Please use PreRelease R556

**Comment by ezfox** [comment]
R556 is working. Thank you!
