### ISSUE TITLE
AirTome crashes on Windows 11 when loading a flightbook.

### ISSUE THREAD

**Issue by vindolin** [AirTome/airtome.github.io#5]
When I first launched a newly installed R547 AirTome, it showed the GUI and I tried to import my old flightbook from my *.fb.zip file and AirTome closed without any error message.

I created a new flightbook, closed AirTome and tried to load the newly created one and it immediately closed again.

Is there anything I can do to pin down the cause?

**Comment by AirTome** [comment]
You can have a look in the logfile. What operating system do you use?

**Comment by vindolin** [comment]
I'm using Windows 11, where can I find the log file?

**Comment by AirTome** [comment]
Logfile should be under c:/Users/yourusername/airtome.userdir

**Comment by vindolin** [comment]
This only seems to happen, when I try to load a flightbook from a Google Drive folder on a network drive on my Synology NAS.

When I copy the file to a local folder and load that in AirTome everything works.

Here are the related lines from the log file:

```
15:45:13.770 	DEBUG	JWindowMenuListener: Öffne Flugbuch ...		
15:45:13.774 	DEBUG	Save XML		
15:45:13.775 	DEBUG	SaveXML finished.		
15:45:22.181 	DEBUG	Flush Cache and lock Flightbook		
15:45:22.182 	INFO	flighbookcontainer: G:\test.fb.zip		
15:45:22.182 	INFO	TFile.exists returns: true		
15:45:22.183 	INFO	TFile.canexecute returns: false		
15:45:22.184 	INFO	TFile.canread returns: true		
15:45:22.184 	INFO	TFile.canwrite returns: false		
15:45:22.185 	INFO	TFile.isarchive returns: true		
15:45:22.185 	INFO	TFile.isentry returns: false		
15:45:22.185 	INFO	TFile.isfile returns: false		
15:45:22.186 	INFO	TFile.isHidden returns: false		
15:45:22.186 	INFO	TFile.isUNC returns: false		
15:45:22.188 	INFO	Try to set write permission: true		
15:45:22.230 	ERROR	### FlushCacheAndLockFlightbook: Can not write to Flightbook: G:\test.fb.zip		
```
I checked and the file is not write protected.

**Comment by AirTome** [comment]
Good Analysis! I will try to reproduce the effect.

**Comment by AirTome** [comment]
Unfortunately I cannot reproduce this effect. Works here with network drives running on a synology nas. Does this happen also if you use a flightbook on a nas network drive? Or is this an effect of a google drive synchronization attempt?

**Comment by vindolin** [comment]
In the meantime I switched from the Synology drive to a local mirrored drive on an external drive and can no longer reproduce the problem.
