### ISSUE TITLE
Date 01.01.2022 counted as week 53 of 2022

### ISSUE THREAD

**Issue by fraza077** [AirTome/airtome.github.io#6]
The graph X-Axis "Week" counts flights done on the 01.01.2022 as being week 53 of 2022. Either they should be week 53 of 2021 or week 1 of 2022. 
![image](https://user-images.githubusercontent.com/14188288/150331597-90256ae4-4a15-41d8-86ae-e77bcdaf73cf.png)

**Comment by AirTome** [comment]
Thank you for reporting and good catch!

**Comment by AirTome** [comment]
Is fixed in Release >547.
