### ISSUE TITLE
FAQ out of date for SRMT data

### ISSUE THREAD

**Issue by nico-krais** [AirTome/airtome.github.io#7]
The website supplying the SRMT data underwent an overhaul.

The new correct link for the Download page is https://srtm.csi.cgiar.org/srtmdata/.

Also the format you must choose on the website is now called "Esri ASCII", which should propably be mentioned.

Unfortunately, you can not supply a pull request for a Wiki (as far as I know), otherwise I would have done that.

**Comment by AirTome** [comment]
Thank you very much! I will change it for the next release.
