### ISSUE TITLE
Feature for quickly summing up the flight hours of selected entries.

### ISSUE THREAD

**Issue by vindolin** [AirTome/airtome.github.io#8]
It would be super nice if there was a function that sums up the flight hours:minutes of selected entries, e.g. for selling a wing.

When I need to know the total flight hours of a wing I export the entries into Google Spreadsheet but that's a lot of effort.

**Comment by AirTome** [comment]
You can do that with the statistics view. Select "Flighttime (total)" for X and for example "ID" for Y (if you use the Glider ID field to differentiate different glider)

**Comment by vindolin** [comment]
Oops, I must have closed the statistic tab sometime in the past 🤦‍♂️
Works great thanks!
