### ISSUE TITLE
Implement Low-pass filter continuously

### ISSUE THREAD

**Issue by fraza077** [AirTome/airtome.github.io#9]
I can't remember what the technical term for this is.

Basically, the 10s/30s filter on graphs appears to average out 30 seconds of samples, then do the next 30-second block, then the next. To get a nice smooth graph, it should average out 30 seconds of samples, then move forward by one sample, and do 30 seconds of samples from there.
You'll end up with almost the same number of datapoints as the original input data; it will be smoothed. It's also how filters like that are mostly implemented. Of course it will be slightly more CPU intensive, but I don't think it will be too bad.

![image](https://user-images.githubusercontent.com/14188288/177473564-4ec8ee18-e9ea-4cc0-bb96-6c6ef7a4249b.png)

I don't know, that wasn't very well explained, sorry.

**Comment by luismaie** [comment]
You are probably thinking about something like a moving average:
https://en.wikipedia.org/wiki/Moving_average

This keeps the points density, but smoothes the result.

**Comment by fraza077** [comment]
Yes exactly, thank you

**Comment by AirTome** [comment]
That's a good idea to implement.

**Comment by AirTome** [comment]
Changed to moving average in >R522
